### PR TITLE
Don't affect global git settings 

### PR DESCRIPTION
**Pull request by ReDetection**

### CODE REVIEW

**Comment by orta** [comment]
What are the downsides to doing it this way?

**Comment by orta** [comment]
Otherwise this only sets it in the folder?

**Comment by ReDetection** [comment]
Yes, only for particular repo.
Why you forcing to have global name and email? this can interfere current git username strategy. E.g. when developer has personal email and organization's one, so for every project I can decide which one to choose. 
In case when developer prefers to keep global git name and email, most likely that he already has them defined as global because noone begin learning programming from creating a pod library, but split some existing app into libs are more frequent scenario

**Comment by orta** [comment]
Thanks @ReDetection - sorry it took me a while to ge back the first time. I think this makes sense, thanks for explaining it :+1:

**Comment by ReDetection** [comment]
no problem :ok_hand:

**Pull request merged**
