### PR TITLE
Add macos-swift template

### PR DESCRIPTION
**Pull request by malt03**

### CODE REVIEW

**Comment by dnkoutso** [comment]
Not super familiar with this project but LGTM. Would love if someone else provides a review though.

**Comment by orta** [comment]
Yeah, this feels good to me, any chance you can change the copyrights on the generated files?

**Comment by malt03** [comment]
Thanks for your suggestion.
I will change them.

**Comment by malt03** [comment]
@orta fixed

**Comment by orta** [comment]
Cool, yep, looks 👍 

Lets do it

**Pull request merged**
