### PR TITLE
Supply a sample description in podspec as it breaks pod lib create without one

### PR DESCRIPTION
**Pull request by thomasgallagher**

### CODE REVIEW

**Comment by Coeur** [comment]
A lorem ipsum is more for a visual preview.
A more meaningful stub would be "TODO: add long description of the pod here".

**Comment by orta** [comment]
Aye, I think I'm with @Coeur on this one, any chance you can make it the: `TODO: add long description of the pod here` please? - then this is good to go - thanks @thomasgallagher

**Comment by thomasgallagher** [comment]
Here you go - also referenced an open issue.

Happy to help :)

**Comment by orta** [comment]
👍

**Pull request merged**
