### PR TITLE
Update the podspecs copy to match cocoapods' new defaults

### PR DESCRIPTION
**Pull request by orta**
Corresponds with https://github.com/CocoaPods/CocoaPods/pull/3984

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:

**Comment by kylef** [comment]
Remember to update the podspec linter in https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/linter.rb#L247, currently it displays a warning if the user didn't change the description from the default value. Since you're changing the default value, the linter should be amended to show a warning for the new default too.

**Comment by kylef** [comment]
Otherwise :+1:.

**Comment by segiddins** [comment]
@orta feel free to merge this once you've addressed kyle's comment :)

**Comment by orta** [comment]
PR sent

**Comment by orta** [comment]
This will get caught by the current linter for being shorter than the summary too ATM. So I'm good to go.

**Pull request merged**
