### PR TITLE
New project layout, Carthage, SPM [WIP]

### LINKED ISSUE #79: Create a full test
We should have a repo which is the result of pod-template which specific arguments. Then a test that runs though the same options and then does a diff on output.

Similar to https://github.com/QueryKit/mogenerator-template/blob/master/Makefile#L7-8. We don't need any complex ruby, simple diff does the job.

This should give us more visibility on the [output and how it looks](https://github.com/QueryKit/mogenerator-template/tree/master/Example), and also allows us to know when we unintentionally break something.

### LINKED ISSUE #131: Recommended project settings
Test case:

1. `pod lib create PROJECT`
2. Open XCode on the workspace
3. Product -> Run

Expected:

Builds with no errors

Actual:

A warning is generated for Pods.xcodeproj titled "Update to recommended settings"

screen shot 2015-11-01 at 4 00 41 pm

### LINKED ISSUE #157: Achieve full compatibility with Swift Package Manager
Update the template layout so that libraries started with `pod-template` will automatically be usable from Swift Package Manager.

TEST CASES:

  * Set up a project with Swift Package Manager like at https://swift.org/package-manager/#example-usage and ensure this library is usable
  * Set up a project with Carthage and ensure no regressions

### PR DESCRIPTION
**Pull request by fulldecent**
This is an ambitious PR that changes the project layout and closes most open issues. **Please help** by *playing* with the proposed code and *contributing* code fixes or test cases of things that are broken.

# How can I play with this PR?

- Clone and `cd` into the directory
- Run some stuff you need to run for any Ruby project:
  - `gem install bundler`
  - `bundle install`
- Run the included test suite:
  - `rake`
  - Note: this uses the latest released version of CocoaPods to run this template (retrieved with Bundler)
- Try it for real:
  - `cd ~/Desktop`
  - `pod lib create --verbose --template-url='file:///PATH/TO/pod-template' NewPod`
  - Note: this uses your INSTALLED VERSION of `pod` to run this template

----

# PR Status

## Wording:

 * pod-template -- this project
 * template -- a model that can have things changed
 * vendored -- a chosen template with variable substitutions and other updates applied and ready for making an iOS framework

## pod-template progress:

- [x] Make vendoring work
- [x] Set up testing with rake/rspec to validate the vendoring process (fixes #79)
- [x] Set up Travis CI
- [x] Update variable substitution process, remove unused code

## baseline template progress: (new feature)

- [x] Move all files common to Swift and Objective-C into a "baseline" template
- [x] Update to latest gitignore
- [x] Supports Swift Package Manager format (fixes #157)

## swift template progress:

- [x] Create a hello world example (this is a change), it actually does something
- [x] Remove FDChessboardView and my name from project, use variable substitution
- [x] Remove XCode warnings (fixes #131)
- [x] Has "hello world"-level functionality

## objective-c template progress: [HELP REQUESTED]

- [ ] Translate the current Swift template into Objective-C

## other blockers:

**PLEASE HELP REVIEW AND ADD BLOCKERS HERE**

- [ ] Confirm each set of options works [HELP REQUESTED]

### CODE REVIEW

**Comment by fulldecent** [comment]
Please assist me in getting this merged into `develop` quickly. This is a big change (but strictly speaking does not break API) -- and it will help if others can commit to develop and open PRs against this progress so far.

THEN I can make a separate PR from develop to master to discuss all blockers anything that might be broken.

Thank you!

**Comment by fulldecent** [comment]
@orta May I please have a clean working slate for this work? 

Merging this #179 into develop gives me the extra problem that f539662be0d690f63d99e4dd8bb17c5971f3c1cc is currently breaking.

Could this instead be merged into a new branch.

**Comment by fulldecent** [comment]
Also, just because I have nowhere better to discuss this, could the `vanilla-xcodebuild` branch please be deleted.

**Comment by orta** [comment]
Sure, what commit ref do you want the branch off?

**Comment by fulldecent** [comment]
Please branch off master and then this PR is ready to be immediately merged into that new branch.

**Comment by orta** [comment]
Develop is based off master, should be 👍

**Comment by fulldecent** [comment]
Right now there are a couple extra commits in develop that are incompatible with this branch. Please advise

**Comment by orta** [comment]
I'm not really sure what the commits or the merge conflicts are, I assume these are PRs that came in while this was WIP? If they seem useful take the code, if they don't drop them, given this is mostly are-write it's fine to rethink

**Comment by fulldecent** [comment]
OK, I just did a `git merge --strategy ours upstream/develop`. This is ready to merge to develop!

**Comment by orta** [comment]
Awesome!

**Comment by orta** [comment]
awesome

**Comment by fulldecent** [comment]
Thank you! Discussion continued at https://github.com/CocoaPods/pod-template/pull/183

**Pull request merged**
