### PR TITLE
Try to fix build creation issue #111

### PR DESCRIPTION
**Pull request by leverdeterre**
I' encountered the same problem actually on the pod lib create command

### CODE REVIEW

**Comment by orta** [comment]
This is good, but a few of those changes undo the quotes around "PROJECT" which means that we can't support spaces in pod names, any chance you can edit those back in?

**Comment by kylef** [comment]
@orta Spaces in pod names are not permitted in CocoaPods itself.

**Comment by cameroncooke** [comment]
This fixes the problem for me that prevented me from creating a new Cocoapod.

**Comment by orta** [comment]
Perfect, thanks @leverdeterre / @cameroncooke !

**Pull request merged**
