### PR TITLE
ObjC Template: Removing unused, deprecating launch images for launch screen.

### PR DESCRIPTION
**Pull request by jugutier**
Removing unused asset catalog and Launch Images Source in favor of Launch screen. Keeping asset catalog name Images.xcassets in parity with swift template

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
If you're feeling brave, you could consider adding Objective-C support to https://github.com/CocoaPods/pod-template/pull/187 ;)

**Comment by jugutier** [comment]
yes! I'll make that this week's task  @orta :)

**Comment by orta** [comment]
<3

**Pull request merged**
