### PR TITLE
Fixes #157

### LINKED ISSUE #157: Achieve full compatibility with Swift Package Manager
Update the template layout so that libraries started with `pod-template` will automatically be usable from Swift Package Manager.

TEST CASES:

  * Set up a project with Swift Package Manager like at https://swift.org/package-manager/#example-usage and ensure this library is usable
  * Set up a project with Carthage and ensure no regressions

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by orta** [comment]
Is this a work in progress? This doesn't add support for SPM, there are specific build folder structures to my knowledge, it should require quite a bit of work I think.

**Comment by fulldecent** [comment]
I have only copied the work from AlamoFire. I am assuming they have this figured out already.

**Comment by fulldecent** [comment]
I have been trying to understand AlamoFire's layout and bring those ideas into pod-template. But this is definitely over my head. (Then I thought about just making an issue and getting my company to set a bounty, but even that is over my head.)

**Comment by orta** [comment]
I think an approach to tackle this would be to write one or two working swift packages from scratch, that work as expected with swiftpm, then take the ideas from that back to this project

**Comment by fulldecent** [comment]
Sounds good, closing PR for now.

**Comment by orta** [comment]
👍

**Pull request closed without merging**
