### PR TITLE
New project layout, Carthage, SPM [WIP]

### LINKED ISSUE #79: Create a full test
We should have a repo which is the result of pod-template which specific arguments. Then a test that runs though the same options and then does a diff on output.

Similar to https://github.com/QueryKit/mogenerator-template/blob/master/Makefile#L7-8. We don't need any complex ruby, simple diff does the job.

This should give us more visibility on the [output and how it looks](https://github.com/QueryKit/mogenerator-template/tree/master/Example), and also allows us to know when we unintentionally break something.

### LINKED ISSUE #131: Recommended project settings
Test case:

1. `pod lib create PROJECT`
2. Open XCode on the workspace
3. Product -> Run

Expected:

Builds with no errors

Actual:

A warning is generated for Pods.xcodeproj titled "Update to recommended settings"

screen shot 2015-11-01 at 4 00 41 pm

### LINKED ISSUE #157: Achieve full compatibility with Swift Package Manager
Update the template layout so that libraries started with `pod-template` will automatically be usable from Swift Package Manager.

TEST CASES:

  * Set up a project with Swift Package Manager like at https://swift.org/package-manager/#example-usage and ensure this library is usable
  * Set up a project with Carthage and ensure no regressions

### PR DESCRIPTION
**Pull request by fulldecent**
The develop branch contains a new projects layout and closes most open issues. **Please help** by *playing* with the proposed code and *contributing* code fixes or test cases of things that are broken.

# How can I play with this PR?

- Clone and `cd` into the directory
- Run some stuff you need to run for any Ruby project:
  - `gem install bundler`
  - `bundle install`
- Run the included test suite:
  - `rake`
  - Note: this uses the latest released version of CocoaPods to run this template (retrieved with Bundler above)
- Try it for real:
  - `cd ~/Desktop`
  - `pod lib create --verbose --template-url='file:///PATH/TO/pod-template' NewPod`
  - Note: this uses your INSTALLED VERSION of `pod` to run this template
- Hacking:
  - **Note: you MUST commit to git BEFORE you do `rake` testing or `pod lib create` testing. Both of those tools pull from master in your local repository. Learn how to squash commits :-)**

----

# PR Status

## Wording:

 * pod-template -- this project
 * template -- a model that can have things changed
 * vendored -- a chosen template with variable substitutions and other updates applied and ready for making an iOS framework

## pod-template progress:

- [x] Make vendoring work
- [x] Set up testing with rake/rspec to validate the vendoring process (fixes #79)
- [x] Set up Travis CI
- [x] Update variable substitution process, remove unused code

## baseline template progress: (new feature)

- [x] Move all files common to Swift and Objective-C into a "baseline" template
- [x] Update to latest gitignore
- [x] Supports Swift Package Manager format (fixes #157)

## swift template progress:

- [x] Create a hello world example (this is a change), it actually does something
- [x] Remove FDChessboardView and my name from project, use variable substitution
- [x] Remove XCode warnings (fixes #131)
- [x] Has "hello world"-level functionality

## objective-c template progress: [HELP REQUESTED]

- [ ] Translate the current Swift template into Objective-C

## other blockers:

**PLEASE HELP REVIEW AND ADD BLOCKERS HERE**

- [ ] Confirm each set of options works [HELP REQUESTED]
- [ ] Update readme with PLAYING WITH PR notes above

### CODE REVIEW

**Comment by fulldecent** [comment]
@orta Now that this is in develop, you have commit access and I don't. I can continue to make bite-sized PRs into this develop branch. But please help me get a better handle on what to do, so that I'm moving in the right direction :-)

**Comment by fulldecent** [comment]
@orta FYI, I'm also on IRC if all these emails weren't already annoying enough :-)

**Comment by orta** [comment]
Added you as a contributor too, you shouldn't be blocked by me

**Comment by fulldecent** [comment]
Cool thank you

**Pull request closed without merging**
