### PR TITLE
Fixes #98, per CocoaPods/CocoaPods

### LINKED ISSUE #98: Include a Code of Conduct?
http://contributor-covenant.org

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by segiddins** [comment]
Does this make adding the code of conduct opt-in? Without that, I'm afraid we'd be devaluing the statement of having a CoC

**Comment by fulldecent** [comment]
I know nothing about this. But I think the policy should be decided in the CocoaPods/CocoaPods repository and we should mirror their decision here.

**Comment by orta** [comment]
Yeah, this does just add it to a library without the consent of an author.
In order for it to be of value we should ask in a way [similar to Bundler](https://github.com/bundler/bundler/blob/master/lib/bundler/cli/gem.rb#L99) - though theirs is considerably more wordy than CPs on average, I'd be happy to start there then par it down

**Comment by fulldecent** [comment]
Oh, we are talking about adding CoC to the *vendored* project!?

No, I do not think that is a "very strongly encouraged best practice". Maybe some day, but not today.

My PR adds CoC to the unvendored `pod-template` project.

**Comment by orta** [comment]
Ace, then this is a go.

**Pull request merged**
